repository:
    name: gokanlogic
    owner: gitrdm
    description: '[![Version](https://img.shields.io/badge/version-1.0.1-blue.svg)](https://github.com/gitrdm/gokanlogic/releases)'
    import_path: github.com/gitrdm/gokanlogic
    branch: master
    url: https://github.com/gitrdm/gokanlogic
output:
    directory: /home/rdmerrio/gits/gokanlogic/docs
    clean: false
    gitbook_config: true
discovery:
    packages:
        auto_discover: true
        include_patterns:
            - ./pkg/...
        exclude_patterns:
            - ./vendor/...
            - ./test/...
            - ./.git/...
            - ./examples/...
            - ./cmd/...
            - '**/*_test.go'
        manual_packages: []
    api_generation:
        enabled: true
        include_unexported: false
        include_tests: false
        include_examples: true
    examples:
        enabled: false
        auto_discover: false
        directories: []
    guides:
        enabled: true
        include_contributing: true
        include_faq: true
        custom_guides: []
templates:
    directory: ""
    custom_templates: []
gitbook:
    title: gokanlogic
    description: '[![Version](https://img.shields.io/badge/version-1.0.1-blue.svg)](https://github.com/gitrdm/gokanlogic/releases)'
    theme: default
    plugins: []
    structure:
        readme: README.md
        summary: SUMMARY.md
metadata:
    version: latest
    go_version: ""
    author: ""
    license: MIT
generation:
    date_format: "2006-01-02"
    include_generated_notice: true
    include_toc: true
    max_depth: 3
